version: "3.8"

services:
  app:
    container_name: react-mini-note-app
    image: react-mini-note-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_SIGNUP_CONFIRMATION_MODE=${NEXT_PUBLIC_SIGNUP_CONFIRMATION_MODE}
    ports:
      - 3090:3000
      - 9299:9229
